/* =========================================================
   TRIVIA DEL CUMPLE — preguntas (con subtítulos en japonés)

   ✏️ EDITÁ ACÁ LAS PREGUNTAS
   En cada partida se eligen al azar PREGUNTAS_POR_PARTIDA (config.js)
   de esta lista, y no se repiten entre partidas hasta que salieron todas
   (con 80 preguntas y 20 por partida: 4 partidas sin repetir).

   - id:         número único (sirve para no repetir preguntas entre partidas).
   - pregunta:   el texto que se ve en grande en la TV.
   - preguntaJa: subtítulo en japonés de la pregunta (opcional).
   - opciones:   de 2 a 4 respuestas. El orden define el color y la forma:
                 1ª 🔺 roja · 2ª 🔷 azul · 3ª 🟡 amarilla · 4ª 🟩 verde.
   - opcionesJa: subtítulos en japonés, en el mismo orden que "opciones" (opcional).
   - correcta:   posición de la respuesta correcta, contando desde 0
                 (0 = la primera, 1 = la segunda, 2 = la tercera, 3 = la cuarta).
   - tiempo:     segundos para responder.

   Los subtítulos se prenden o apagan con MOSTRAR_JAPONES en config.js.

   Ojo: este archivo es público en la web; un invitado muy curioso podría
   leer las respuestas. Para un cumple alcanza.
   ========================================================= */
'use strict';

const PREGUNTAS = [
  // ---------- Ciencia y naturaleza ----------
  {
    id: 1,
    pregunta: '¿Cuál es el planeta más grande del sistema solar?',
    preguntaJa: '太陽系で一番大きい惑星は？',
    opciones: ['Marte', 'Júpiter', 'Saturno', 'Neptuno'],
    opcionesJa: ['火星', '木星', '土星', '海王星'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 2,
    pregunta: '¿Cuál es el planeta más cercano al Sol?',
    preguntaJa: '太陽に一番近い惑星は？',
    opciones: ['Venus', 'Tierra', 'Marte', 'Mercurio'],
    opcionesJa: ['金星', '地球', '火星', '水星'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 3,
    pregunta: '¿Qué planeta es conocido como "el planeta rojo"?',
    preguntaJa: '「赤い惑星」と呼ばれる惑星は？',
    opciones: ['Marte', 'Venus', 'Júpiter', 'Mercurio'],
    opcionesJa: ['火星', '金星', '木星', '水星'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 4,
    pregunta: '¿Cuántas patas tiene una araña?',
    preguntaJa: 'クモの脚は何本？',
    opciones: ['6', '10', '8', '12'],
    opcionesJa: ['6本', '10本', '8本', '12本'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 5,
    pregunta: '¿Cuántos corazones tiene un pulpo?',
    preguntaJa: 'タコの心臓はいくつ？',
    opciones: ['1', '3', '2', '4'],
    opcionesJa: ['1つ', '3つ', '2つ', '4つ'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 6,
    pregunta: '¿Cuál es el animal más grande del planeta?',
    preguntaJa: '地球上で一番大きい動物は？',
    opciones: ['Elefante africano', 'Tiburón ballena', 'Jirafa', 'Ballena azul'],
    opcionesJa: ['アフリカゾウ', 'ジンベエザメ', 'キリン', 'シロナガスクジラ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 7,
    pregunta: '¿Qué ave pone los huevos más grandes?',
    preguntaJa: '一番大きい卵を産む鳥は？',
    opciones: ['Avestruz', 'Emú', 'Cóndor', 'Pingüino emperador'],
    opcionesJa: ['ダチョウ', 'エミュー', 'コンドル', 'コウテイペンギン'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 8,
    pregunta: '¿Qué gas toman las plantas del aire para hacer la fotosíntesis?',
    preguntaJa: '植物が光合成のために空気から取り込む気体は？',
    opciones: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Helio'],
    opcionesJa: ['酸素', '窒素', '二酸化炭素', 'ヘリウム'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 9,
    pregunta: '¿Cuál es el gas más abundante en el aire que respiramos?',
    preguntaJa: '私たちが吸う空気に一番多く含まれている気体は？',
    opciones: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Argón'],
    opcionesJa: ['酸素', '窒素', '二酸化炭素', 'アルゴン'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 10,
    pregunta: '¿Qué metal tiene el símbolo químico "Au"?',
    preguntaJa: '元素記号が「Au」の金属は？',
    opciones: ['Plata', 'Aluminio', 'Cobre', 'Oro'],
    opcionesJa: ['銀', 'アルミニウム', '銅', '金'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 11,
    pregunta: '¿Qué vitamina produce el cuerpo cuando le da el sol?',
    preguntaJa: '日光を浴びると体の中で作られるビタミンは？',
    opciones: ['Vitamina D', 'Vitamina C', 'Vitamina A', 'Vitamina K'],
    opcionesJa: ['ビタミンD', 'ビタミンC', 'ビタミンA', 'ビタミンK'],
    correcta: 0,
    tiempo: 15,
  },

  // ---------- Cuerpo humano ----------
  {
    id: 12,
    pregunta: '¿Cuál es el hueso más largo del cuerpo humano?',
    preguntaJa: '人体で一番長い骨は？',
    opciones: ['Húmero', 'Fémur', 'Tibia', 'Peroné'],
    opcionesJa: ['上腕骨', '大腿骨', '脛骨', '腓骨'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 13,
    pregunta: '¿Cuántos huesos tiene el cuerpo de una persona adulta?',
    preguntaJa: '大人の体には骨がいくつある？',
    opciones: ['106', '306', '206', '406'],
    opcionesJa: ['106個', '306個', '206個', '406個'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 14,
    pregunta: '¿Cuál es el órgano más grande del cuerpo humano?',
    preguntaJa: '人体で一番大きい器官は？',
    opciones: ['Hígado', 'Cerebro', 'Pulmones', 'Piel'],
    opcionesJa: ['肝臓', '脳', '肺', '皮膚'],
    correcta: 3,
    tiempo: 20,
  },

  // ---------- Geografía ----------
  {
    id: 15,
    pregunta: '¿Cuál es la capital de Australia?',
    preguntaJa: 'オーストラリアの首都は？',
    opciones: ['Sídney', 'Canberra', 'Melbourne', 'Perth'],
    opcionesJa: ['シドニー', 'キャンベラ', 'メルボルン', 'パース'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 16,
    pregunta: '¿Cuál es la capital de Canadá?',
    preguntaJa: 'カナダの首都は？',
    opciones: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    opcionesJa: ['オタワ', 'トロント', 'バンクーバー', 'モントリオール'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 17,
    pregunta: '¿Cuál es la capital de Brasil?',
    preguntaJa: 'ブラジルの首都は？',
    opciones: ['Río de Janeiro', 'San Pablo', 'Brasilia', 'Salvador'],
    opcionesJa: ['リオデジャネイロ', 'サンパウロ', 'ブラジリア', 'サルバドール'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 18,
    pregunta: '¿Cuál es el país más grande del mundo?',
    preguntaJa: '世界で一番面積が大きい国は？',
    opciones: ['China', 'Estados Unidos', 'Canadá', 'Rusia'],
    opcionesJa: ['中国', 'アメリカ', 'カナダ', 'ロシア'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 19,
    pregunta: '¿Cuál es el océano más grande del mundo?',
    preguntaJa: '世界で一番大きい海洋は？',
    opciones: ['Atlántico', 'Pacífico', 'Índico', 'Ártico'],
    opcionesJa: ['大西洋', '太平洋', 'インド洋', '北極海'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 20,
    pregunta: '¿Cuál es la montaña más alta del mundo?',
    preguntaJa: '世界で一番高い山は？',
    opciones: ['K2', 'Aconcagua', 'Everest', 'Kilimanjaro'],
    opcionesJa: ['K2', 'アコンカグア', 'エベレスト', 'キリマンジャロ'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 21,
    pregunta: '¿Cuál es la montaña más alta de América?',
    preguntaJa: 'アメリカ大陸で一番高い山は？',
    opciones: ['Aconcagua', 'Denali', 'Chimborazo', 'Huascarán'],
    opcionesJa: ['アコンカグア', 'デナリ', 'チンボラソ', 'ワスカラン'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 22,
    pregunta: '¿Cuál es el río más largo de América del Sur?',
    preguntaJa: '南米で一番長い川は？',
    opciones: ['Paraná', 'Orinoco', 'Río de la Plata', 'Amazonas'],
    opcionesJa: ['パラナ川', 'オリノコ川', 'ラプラタ川', 'アマゾン川'],
    correcta: 3,
    tiempo: 20,
  },
  {
    id: 23,
    pregunta: '¿Cuál es el desierto más seco del mundo (sin contar los polos)?',
    preguntaJa: '極地を除いて、世界で一番乾燥した砂漠は？',
    opciones: ['Sahara', 'Atacama', 'Gobi', 'Kalahari'],
    opcionesJa: ['サハラ砂漠', 'アタカマ砂漠', 'ゴビ砂漠', 'カラハリ砂漠'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 24,
    pregunta: '¿En qué continente está Kenia?',
    preguntaJa: 'ケニアはどの大陸にある？',
    opciones: ['Asia', 'Oceanía', 'África', 'América'],
    opcionesJa: ['アジア', 'オセアニア', 'アフリカ', 'アメリカ大陸'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 25,
    pregunta: '¿En qué país están las pirámides de Guiza?',
    preguntaJa: 'ギザのピラミッドがある国は？',
    opciones: ['Egipto', 'México', 'Perú', 'India'],
    opcionesJa: ['エジプト', 'メキシコ', 'ペルー', 'インド'],
    correcta: 0,
    tiempo: 15,
  },

  // ---------- Historia, arte y cultura ----------
  {
    id: 26,
    pregunta: '¿Quién pintó la Mona Lisa?',
    preguntaJa: '「モナ・リザ」を描いたのは誰？',
    opciones: ['Pablo Picasso', 'Miguel Ángel', 'Vincent van Gogh', 'Leonardo da Vinci'],
    opcionesJa: ['パブロ・ピカソ', 'ミケランジェロ', 'フィンセント・ファン・ゴッホ', 'レオナルド・ダ・ヴィンチ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 27,
    pregunta: '¿Quién pintó "La noche estrellada"?',
    preguntaJa: '「星月夜」を描いたのは誰？',
    opciones: ['Claude Monet', 'Vincent van Gogh', 'Salvador Dalí', 'Pablo Picasso'],
    opcionesJa: ['クロード・モネ', 'フィンセント・ファン・ゴッホ', 'サルバドール・ダリ', 'パブロ・ピカソ'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 28,
    pregunta: '¿Quién escribió "Don Quijote de la Mancha"?',
    preguntaJa: '『ドン・キホーテ』を書いたのは誰？',
    opciones: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Miguel de Cervantes', 'Lope de Vega'],
    opcionesJa: ['ホルヘ・ルイス・ボルヘス', 'ガブリエル・ガルシア＝マルケス', 'ミゲル・デ・セルバンテス', 'ロペ・デ・ベガ'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 29,
    pregunta: '¿En qué año llegó el ser humano a la Luna por primera vez?',
    preguntaJa: '人類が初めて月に降り立ったのは何年？',
    opciones: ['1965', '1969', '1967', '1972'],
    opcionesJa: ['1965年', '1969年', '1967年', '1972年'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 30,
    pregunta: '¿En qué año cayó el Muro de Berlín?',
    preguntaJa: 'ベルリンの壁が崩壊したのは何年？',
    opciones: ['1989', '1985', '1991', '1995'],
    opcionesJa: ['1989年', '1985年', '1991年', '1995年'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 31,
    pregunta: '¿Qué científico propuso la teoría de la relatividad?',
    preguntaJa: '相対性理論を提唱した科学者は？',
    opciones: ['Isaac Newton', 'Galileo Galilei', 'Nikola Tesla', 'Albert Einstein'],
    opcionesJa: ['アイザック・ニュートン', 'ガリレオ・ガリレイ', 'ニコラ・テスラ', 'アルベルト・アインシュタイン'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 32,
    pregunta: '¿Qué banda grabó el disco "Abbey Road"?',
    preguntaJa: 'アルバム『アビイ・ロード』を出したバンドは？',
    opciones: ['The Rolling Stones', 'Queen', 'The Beatles', 'Pink Floyd'],
    opcionesJa: ['ローリング・ストーンズ', 'クイーン', 'ビートルズ', 'ピンク・フロイド'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 33,
    pregunta: '¿Qué idioma se habla oficialmente en Brasil?',
    preguntaJa: 'ブラジルの公用語は？',
    opciones: ['Español', 'Portugués', 'Brasileño', 'Inglés'],
    opcionesJa: ['スペイン語', 'ポルトガル語', 'ブラジル語', '英語'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 34,
    pregunta: '¿Cuál es el idioma con más hablantes nativos del mundo?',
    preguntaJa: '母語として話す人が世界で一番多い言語は？',
    opciones: ['Chino mandarín', 'Inglés', 'Español', 'Hindi'],
    opcionesJa: ['中国語（標準中国語）', '英語', 'スペイン語', 'ヒンディー語'],
    correcta: 0,
    tiempo: 20,
  },

  // ---------- Deportes y música ----------
  {
    id: 35,
    pregunta: '¿Qué selección ganó el Mundial de fútbol de 2022?',
    preguntaJa: '2022年サッカーワールドカップの優勝国は？',
    opciones: ['Francia', 'Brasil', 'Croacia', 'Argentina'],
    opcionesJa: ['フランス', 'ブラジル', 'クロアチア', 'アルゼンチン'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 36,
    pregunta: '¿Cuántos jugadores tiene un equipo de vóley en la cancha?',
    preguntaJa: 'バレーボールでコートに入る1チームの人数は？',
    opciones: ['5', '6', '7', '9'],
    opcionesJa: ['5人', '6人', '7人', '9人'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 37,
    pregunta: '¿Cuántas cuerdas tiene una guitarra criolla?',
    preguntaJa: 'クラシックギターの弦は何本？',
    opciones: ['4', '5', '6', '7'],
    opcionesJa: ['4本', '5本', '6本', '7本'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 38,
    pregunta: '¿Cuántas teclas tiene un piano estándar?',
    preguntaJa: '標準的なピアノの鍵盤はいくつ？',
    opciones: ['88', '76', '96', '104'],
    opcionesJa: ['88鍵', '76鍵', '96鍵', '104鍵'],
    correcta: 0,
    tiempo: 20,
  },

  // ---------- Curiosidades ----------
  {
    id: 39,
    pregunta: '¿De qué color es la "caja negra" de los aviones?',
    preguntaJa: '飛行機の「ブラックボックス」は何色？',
    opciones: ['Negra', 'Roja', 'Naranja', 'Amarilla'],
    opcionesJa: ['黒', '赤', 'オレンジ', '黄色'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 40,
    pregunta: '¿Qué fruta tiene las semillas por fuera?',
    preguntaJa: '種が実の外側についている果物は？',
    opciones: ['Kiwi', 'Banana', 'Uva', 'Frutilla'],
    opcionesJa: ['キウイ', 'バナナ', 'ブドウ', 'イチゴ'],
    correcta: 3,
    tiempo: 15,
  },

  // ---------- Cine ----------
  {
    id: 41,
    pregunta: '¿Cómo se llama el barco de la película de James Cameron de 1997?',
    preguntaJa: '1997年のジェームズ・キャメロン監督作品に登場する豪華客船の名前は？',
    opciones: ['Titanic', 'Britannic', 'Olympic', 'Lusitania'],
    opcionesJa: ['タイタニック号', 'ブリタニック号', 'オリンピック号', 'ルシタニア号'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 42,
    pregunta: 'En "El Rey León", ¿cómo se llama el papá de Simba?',
    preguntaJa: '『ライオン・キング』で、シンバのお父さんの名前は？',
    opciones: ['Scar', 'Mufasa', 'Rafiki', 'Zazú'],
    opcionesJa: ['スカー', 'ムファサ', 'ラフィキ', 'ザズー'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 43,
    pregunta: 'En "Toy Story", ¿cómo se llama el muñeco vaquero?',
    preguntaJa: '『トイ・ストーリー』のカウボーイ人形の名前は？',
    opciones: ['Buzz', 'Rex', 'Woody', 'Hamm'],
    opcionesJa: ['バズ', 'レックス', 'ウッディ', 'ハム'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 44,
    pregunta: '¿En qué casa de Hogwarts está Harry Potter?',
    preguntaJa: 'ハリー・ポッターが入ったホグワーツの寮は？',
    opciones: ['Slytherin', 'Ravenclaw', 'Hufflepuff', 'Gryffindor'],
    opcionesJa: ['スリザリン', 'レイブンクロー', 'ハッフルパフ', 'グリフィンドール'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 45,
    pregunta: 'En "Star Wars", ¿quién es el padre de Luke Skywalker?',
    preguntaJa: '『スター・ウォーズ』で、ルーク・スカイウォーカーの父親は？',
    opciones: ['Darth Vader', 'Obi-Wan Kenobi', 'Yoda', 'Han Solo'],
    opcionesJa: ['ダース・ベイダー', 'オビ＝ワン・ケノービ', 'ヨーダ', 'ハン・ソロ'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 46,
    pregunta: '¿Qué película argentina ganó el Oscar a mejor película extranjera en 2010?',
    preguntaJa: '2010年にアカデミー外国語映画賞を受賞したアルゼンチン映画は？',
    opciones: ['Relatos salvajes', 'Nueve reinas', 'El secreto de sus ojos', 'Argentina, 1985'],
    opcionesJa: ['人生スイッチ', 'ナイン・クイーンズ', '瞳の奥の秘密', 'アルゼンチン1985'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 47,
    pregunta: 'En "Buscando a Nemo", ¿qué tipo de pez es Nemo?',
    preguntaJa: '『ファインディング・ニモ』のニモは何の魚？',
    opciones: ['Pez cirujano', 'Pez payaso', 'Pez globo', 'Pez espada'],
    opcionesJa: ['ナンヨウハギ', 'カクレクマノミ', 'フグ', 'メカジキ'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 48,
    pregunta: 'En "Frozen", ¿cómo se llama la reina con poderes de hielo?',
    preguntaJa: '『アナと雪の女王』で、氷の魔法を使う女王の名前は？',
    opciones: ['Anna', 'Ariel', 'Rapunzel', 'Elsa'],
    opcionesJa: ['アナ', 'アリエル', 'ラプンツェル', 'エルサ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 49,
    pregunta: 'En "Volver al futuro", ¿qué auto usan como máquina del tiempo?',
    preguntaJa: '『バック・トゥ・ザ・フューチャー』で、タイムマシンになる車は？',
    opciones: ['DeLorean', 'Ford Mustang', 'Chevrolet Camaro', 'Volkswagen Escarabajo'],
    opcionesJa: ['デロリアン', 'フォード・マスタング', 'シボレー・カマロ', 'フォルクスワーゲン・ビートル'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 50,
    pregunta: '¿Qué actor interpreta a Jack Sparrow en "Piratas del Caribe"?',
    preguntaJa: '『パイレーツ・オブ・カリビアン』でジャック・スパロウを演じた俳優は？',
    opciones: ['Orlando Bloom', 'Brad Pitt', 'Johnny Depp', 'Leonardo DiCaprio'],
    opcionesJa: ['オーランド・ブルーム', 'ブラッド・ピット', 'ジョニー・デップ', 'レオナルド・ディカプリオ'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 51,
    pregunta: '¿Cuál de estas películas de Studio Ghibli ganó el Oscar a mejor película animada?',
    preguntaJa: 'この中で、アカデミー長編アニメ映画賞を受賞したスタジオジブリ作品は？',
    opciones: ['Mi vecino Totoro', 'El viaje de Chihiro', 'La princesa Mononoke', 'El increíble castillo vagabundo'],
    opcionesJa: ['となりのトトロ', '千と千尋の神隠し', 'もののけ姫', 'ハウルの動く城'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 52,
    pregunta: 'En "Shrek", ¿qué animal es el mejor amigo de Shrek?',
    preguntaJa: '『シュレック』で、シュレックの親友になる動物は？',
    opciones: ['Un gato', 'Un dragón', 'Un caballo', 'Un burro'],
    opcionesJa: ['ネコ', 'ドラゴン', 'ウマ', 'ロバ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 53,
    pregunta: '¿Cuántas películas de "Harry Potter" se estrenaron en el cine?',
    preguntaJa: '映画『ハリー・ポッター』シリーズは全部で何作？',
    opciones: ['8', '7', '9', '10'],
    opcionesJa: ['8作', '7作', '9作', '10作'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 54,
    pregunta: 'En "Jurassic Park", ¿de dónde sacan el ADN para clonar dinosaurios?',
    preguntaJa: '『ジュラシック・パーク』で、恐竜をよみがえらせるDNAはどこから取った？',
    opciones: ['De huesos fósiles', 'De huevos congelados', 'De mosquitos en ámbar', 'De plumas antiguas'],
    opcionesJa: ['化石の骨', '冷凍された卵', '琥珀の中の蚊', '古代の羽根'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 55,
    pregunta: 'En "Matrix", ¿de qué color es la pastilla que toma Neo?',
    preguntaJa: '『マトリックス』で、ネオが飲む薬の色は？',
    opciones: ['Azul', 'Roja', 'Verde', 'Amarilla'],
    opcionesJa: ['青', '赤', '緑', '黄色'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 56,
    pregunta: '¿En qué saga se dice "Que la Fuerza te acompañe"?',
    preguntaJa: '「フォースと共にあらんことを」というセリフが出てくる作品は？',
    opciones: ['Star Trek', 'Avatar', 'Dune', 'Star Wars'],
    opcionesJa: ['スター・トレック', 'アバター', 'デューン', 'スター・ウォーズ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 57,
    pregunta: 'En "Frozen", ¿cómo se llama el muñeco de nieve?',
    preguntaJa: '『アナと雪の女王』の雪だるまの名前は？',
    opciones: ['Olaf', 'Sven', 'Kristoff', 'Hans'],
    opcionesJa: ['オラフ', 'スヴェン', 'クリストフ', 'ハンス'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 58,
    pregunta: 'En "Coco", ¿qué celebración mexicana es el centro de la historia?',
    preguntaJa: '『リメンバー・ミー』の物語の中心になっているメキシコのお祭りは？',
    opciones: ['Navidad', 'Día de Muertos', 'Carnaval', 'Día de la Independencia'],
    opcionesJa: ['クリスマス', '死者の日', 'カーニバル', '独立記念日'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 59,
    pregunta: '¿Qué superhéroe es Tony Stark?',
    preguntaJa: 'トニー・スタークはどのスーパーヒーロー？',
    opciones: ['Capitán América', 'Thor', 'Iron Man', 'Hulk'],
    opcionesJa: ['キャプテン・アメリカ', 'ソー', 'アイアンマン', 'ハルク'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 60,
    pregunta: '¿Qué película de 2009 transcurre en el planeta Pandora?',
    preguntaJa: '2009年公開で、惑星パンドラが舞台の映画は？',
    opciones: ['Interestelar', 'Gravedad', 'Wall-E', 'Avatar'],
    opcionesJa: ['インターステラー', 'ゼロ・グラビティ', 'ウォーリー', 'アバター'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 61,
    pregunta: 'En "Forrest Gump", ¿con qué comparaba la vida su mamá?',
    preguntaJa: '『フォレスト・ガンプ／一期一会』で、ママは人生を何にたとえた？',
    opciones: ['Una caja de chocolates', 'Un viaje en tren', 'Una carrera', 'Un partido de ping-pong'],
    opcionesJa: ['チョコレートの箱', '列車の旅', 'かけっこ', '卓球の試合'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 62,
    pregunta: '¿Quién dirigió "Tiburón" y "E.T."?',
    preguntaJa: '『ジョーズ』と『E.T.』を監督したのは誰？',
    opciones: ['George Lucas', 'Steven Spielberg', 'James Cameron', 'Martin Scorsese'],
    opcionesJa: ['ジョージ・ルーカス', 'スティーヴン・スピルバーグ', 'ジェームズ・キャメロン', 'マーティン・スコセッシ'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 63,
    pregunta: '¿Qué película de Pixar transcurre entre las emociones dentro de la cabeza de una nena?',
    preguntaJa: '女の子の頭の中の「感情」たちが主人公のピクサー映画は？',
    opciones: ['Soul', 'Up', 'Intensa-Mente', 'Elementos'],
    opcionesJa: ['ソウルフル・ワールド', 'カールじいさんの空飛ぶ家', 'インサイド・ヘッド', 'マイ・エレメント'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 64,
    pregunta: '¿Quién ganó el Oscar a mejor actor por "El renacido"?',
    preguntaJa: '『レヴェナント：蘇えりし者』でアカデミー主演男優賞を受賞したのは？',
    opciones: ['Brad Pitt', 'Tom Hanks', 'Matt Damon', 'Leonardo DiCaprio'],
    opcionesJa: ['ブラッド・ピット', 'トム・ハンクス', 'マット・デイモン', 'レオナルド・ディカプリオ'],
    correcta: 3,
    tiempo: 20,
  },
  {
    id: 65,
    pregunta: '¿Qué boxeador de ficción interpretó Sylvester Stallone?',
    preguntaJa: 'シルヴェスター・スタローンが演じた架空のボクサーは？',
    opciones: ['Rocky Balboa', 'Apollo Creed', 'Iván Drago', 'Adonis Creed'],
    opcionesJa: ['ロッキー・バルボア', 'アポロ・クリード', 'イワン・ドラゴ', 'アドニス・クリード'],
    correcta: 0,
    tiempo: 15,
  },

  // ---------- Series ----------
  {
    id: 66,
    pregunta: 'En "Los Simpson", ¿a qué bar va siempre Homero?',
    preguntaJa: '『ザ・シンプソンズ』で、ホーマーがいつも通うバーは？',
    opciones: ['Krusty Burger', 'El bar de Moe', 'Kwik-E-Mart', 'El Calabozo del Androide'],
    opcionesJa: ['クラスティー・バーガー', 'モーズ・タバーン', 'クイックEマート', 'アンドロイズ・ダンジョン'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 67,
    pregunta: '¿Cuántos amigos protagonizan "Friends"?',
    preguntaJa: '『フレンズ』の主人公は何人？',
    opciones: ['4', '5', '6', '7'],
    opcionesJa: ['4人', '5人', '6人', '7人'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 68,
    pregunta: 'En "Friends", ¿cómo se llama el café donde se juntan?',
    preguntaJa: '『フレンズ』で、みんなが集まるカフェの名前は？',
    opciones: ["MacLaren's", "Monk's", "Luke's", 'Central Perk'],
    opcionesJa: ['マクラーレンズ', 'モンクス', 'ルークス', 'セントラル・パーク'],
    correcta: 3,
    tiempo: 20,
  },
  {
    id: 69,
    pregunta: 'En "Breaking Bad", ¿de qué trabajaba Walter White al principio?',
    preguntaJa: '『ブレイキング・バッド』で、ウォルター・ホワイトの最初の仕事は？',
    opciones: ['Profesor de química', 'Médico', 'Policía', 'Abogado'],
    opcionesJa: ['化学の先生', '医者', '警察官', '弁護士'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 70,
    pregunta: '¿De qué país es la serie "La casa de papel"?',
    preguntaJa: '『ペーパー・ハウス』はどこの国のドラマ？',
    opciones: ['México', 'España', 'Argentina', 'Colombia'],
    opcionesJa: ['メキシコ', 'スペイン', 'アルゼンチン', 'コロンビア'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 71,
    pregunta: 'En "La casa de papel", ¿de quién es la cara de las máscaras de los ladrones?',
    preguntaJa: '『ペーパー・ハウス』で、強盗たちがかぶる仮面は誰の顔？',
    opciones: ['Guy Fawkes', 'Charles Chaplin', 'Salvador Dalí', 'Pablo Picasso'],
    opcionesJa: ['ガイ・フォークス', 'チャールズ・チャップリン', 'サルバドール・ダリ', 'パブロ・ピカソ'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 72,
    pregunta: '¿De qué país es la serie "El juego del calamar"?',
    preguntaJa: '『イカゲーム』はどこの国のドラマ？',
    opciones: ['Japón', 'China', 'Tailandia', 'Corea del Sur'],
    opcionesJa: ['日本', '中国', 'タイ', '韓国'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 73,
    pregunta: 'En "Stranger Things", ¿cómo se llama la chica con poderes?',
    preguntaJa: '『ストレンジャー・シングス 未知の世界』で、超能力を持つ女の子の名前は？',
    opciones: ['Eleven (Once)', 'Max', 'Nancy', 'Robin'],
    opcionesJa: ['イレブン', 'マックス', 'ナンシー', 'ロビン'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 74,
    pregunta: 'En "Game of Thrones", ¿en qué continente está Desembarco del Rey?',
    preguntaJa: '『ゲーム・オブ・スローンズ』で、キングズ・ランディングがある大陸は？',
    opciones: ['Essos', 'Westeros', 'Narnia', 'Tierra Media'],
    opcionesJa: ['エッソス', 'ウェスタロス', 'ナルニア', '中つ国'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 75,
    pregunta: '¿Qué integrante de los Locos Addams tiene su propia serie en Netflix?',
    preguntaJa: 'Netflixで自分のドラマができたアダムス・ファミリーのメンバーは？',
    opciones: ['Morticia', 'Pericles', 'Merlina', 'La Abuela'],
    opcionesJa: ['モーティシア', 'パグズリー', 'ウェンズデー', 'おばあちゃん'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 76,
    pregunta: 'En "The Office", ¿cómo se llama la empresa de papel?',
    preguntaJa: '『ザ・オフィス』の製紙会社の名前は？',
    opciones: ['Sabre', 'Wernham Hogg', 'Vance Refrigeration', 'Dunder Mifflin'],
    opcionesJa: ['セイバー', 'ワーナム・ホッグ', 'ヴァンス冷蔵', 'ダンダー・ミフリン'],
    correcta: 3,
    tiempo: 20,
  },
  {
    id: 77,
    pregunta: 'En "El Chavo del 8", ¿quién se mete siempre en el barril?',
    preguntaJa: '『チャボ・デル・オチョ』で、いつも樽の中に入っているのは？',
    opciones: ['El Chavo', 'Quico', 'Don Ramón', 'El Profesor Jirafales'],
    opcionesJa: ['チャボ', 'キコ', 'ドン・ラモン', 'ヒラファレス先生'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 78,
    pregunta: 'En "Los Simpson", ¿de qué color es el pelo de Marge?',
    preguntaJa: '『ザ・シンプソンズ』で、マージの髪の色は？',
    opciones: ['Rubio', 'Azul', 'Rojo', 'Violeta'],
    opcionesJa: ['金色', '青', '赤', '紫'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 79,
    pregunta: 'En "Bob Esponja", ¿dónde trabaja Bob?',
    preguntaJa: '『スポンジ・ボブ』で、ボブが働いているお店は？',
    opciones: ['El Balde de Carnada', 'La casa de piña', 'El Crustáceo Cascarudo', 'Fondo de Bikini'],
    opcionesJa: ['チャム・バケツ', 'パイナップルの家', 'カニカーニ', 'ビキニタウン'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 80,
    pregunta: 'En "Casados con hijos", ¿qué personaje hace Guillermo Francella?',
    preguntaJa: '『カサドス・コン・イホス』で、ギジェルモ・フランセージャが演じた役は？',
    opciones: ['Moni Argento', 'Dardo Fuseneco', 'Coqui Argento', 'Pepe Argento'],
    opcionesJa: ['モニ・アルヘント', 'ダルド・フセネコ', 'コキ・アルヘント', 'ペペ・アルヘント'],
    correcta: 3,
    tiempo: 15,
  },
];
