/* =========================================================
   TRIVIA DEL CUMPLE — preguntas (con subtítulos en japonés)

   ✏️ EDITÁ ACÁ LAS PREGUNTAS
   En cada partida se eligen al azar PREGUNTAS_POR_PARTIDA (config.js)
   de esta lista. Si se juega otra partida, se prefieren las que no
   salieron en la anterior.

   - id:         número único (sirve para no repetir preguntas entre partidas).
   - pregunta:   el texto que se ve en grande en la TV.
   - preguntaJa: subtítulo en japonés de la pregunta (opcional).
   - opciones:   de 2 a 4 respuestas. El orden define el color y la forma:
                 1ª 🔺 roja · 2ª 🔷 azul · 3ª 🟡 amarilla · 4ª 🟩 verde.
   - opcionesJa: subtítulos en japonés, en el mismo orden que "opciones" (opcional).
   - correcta:   posición de la respuesta correcta, contando desde 0
                 (0 = la primera, 1 = la segunda, 2 = la tercera, 3 = la cuarta).
   - tiempo:     segundos para responder.

   Los subtítulos se prenden o apagan con MOSTRAR_JAPONES en config.js.

   Ojo: este archivo es público en la web; un invitado muy curioso podría
   leer las respuestas. Para un cumple alcanza.
   ========================================================= */
'use strict';

const PREGUNTAS = [
  // ---------- Ciencia y naturaleza ----------
  {
    id: 1,
    pregunta: '¿Cuál es el planeta más grande del sistema solar?',
    preguntaJa: '太陽系で一番大きい惑星は？',
    opciones: ['Marte', 'Júpiter', 'Saturno', 'Neptuno'],
    opcionesJa: ['火星', '木星', '土星', '海王星'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 2,
    pregunta: '¿Cuál es el planeta más cercano al Sol?',
    preguntaJa: '太陽に一番近い惑星は？',
    opciones: ['Venus', 'Tierra', 'Marte', 'Mercurio'],
    opcionesJa: ['金星', '地球', '火星', '水星'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 3,
    pregunta: '¿Qué planeta es conocido como "el planeta rojo"?',
    preguntaJa: '「赤い惑星」と呼ばれる惑星は？',
    opciones: ['Marte', 'Venus', 'Júpiter', 'Mercurio'],
    opcionesJa: ['火星', '金星', '木星', '水星'],
    correcta: 0,
    tiempo: 15,
  },
  {
    id: 4,
    pregunta: '¿Cuántas patas tiene una araña?',
    preguntaJa: 'クモの脚は何本？',
    opciones: ['6', '10', '8', '12'],
    opcionesJa: ['6本', '10本', '8本', '12本'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 5,
    pregunta: '¿Cuántos corazones tiene un pulpo?',
    preguntaJa: 'タコの心臓はいくつ？',
    opciones: ['1', '3', '2', '4'],
    opcionesJa: ['1つ', '3つ', '2つ', '4つ'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 6,
    pregunta: '¿Cuál es el animal más grande del planeta?',
    preguntaJa: '地球上で一番大きい動物は？',
    opciones: ['Elefante africano', 'Tiburón ballena', 'Jirafa', 'Ballena azul'],
    opcionesJa: ['アフリカゾウ', 'ジンベエザメ', 'キリン', 'シロナガスクジラ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 7,
    pregunta: '¿Qué ave pone los huevos más grandes?',
    preguntaJa: '一番大きい卵を産む鳥は？',
    opciones: ['Avestruz', 'Emú', 'Cóndor', 'Pingüino emperador'],
    opcionesJa: ['ダチョウ', 'エミュー', 'コンドル', 'コウテイペンギン'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 8,
    pregunta: '¿Qué gas toman las plantas del aire para hacer la fotosíntesis?',
    preguntaJa: '植物が光合成のために空気から取り込む気体は？',
    opciones: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Helio'],
    opcionesJa: ['酸素', '窒素', '二酸化炭素', 'ヘリウム'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 9,
    pregunta: '¿Cuál es el gas más abundante en el aire que respiramos?',
    preguntaJa: '私たちが吸う空気に一番多く含まれている気体は？',
    opciones: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Argón'],
    opcionesJa: ['酸素', '窒素', '二酸化炭素', 'アルゴン'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 10,
    pregunta: '¿Qué metal tiene el símbolo químico "Au"?',
    preguntaJa: '元素記号が「Au」の金属は？',
    opciones: ['Plata', 'Aluminio', 'Cobre', 'Oro'],
    opcionesJa: ['銀', 'アルミニウム', '銅', '金'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 11,
    pregunta: '¿Qué vitamina produce el cuerpo cuando le da el sol?',
    preguntaJa: '日光を浴びると体の中で作られるビタミンは？',
    opciones: ['Vitamina D', 'Vitamina C', 'Vitamina A', 'Vitamina K'],
    opcionesJa: ['ビタミンD', 'ビタミンC', 'ビタミンA', 'ビタミンK'],
    correcta: 0,
    tiempo: 15,
  },

  // ---------- Cuerpo humano ----------
  {
    id: 12,
    pregunta: '¿Cuál es el hueso más largo del cuerpo humano?',
    preguntaJa: '人体で一番長い骨は？',
    opciones: ['Húmero', 'Fémur', 'Tibia', 'Peroné'],
    opcionesJa: ['上腕骨', '大腿骨', '脛骨', '腓骨'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 13,
    pregunta: '¿Cuántos huesos tiene el cuerpo de una persona adulta?',
    preguntaJa: '大人の体には骨がいくつある？',
    opciones: ['106', '306', '206', '406'],
    opcionesJa: ['106個', '306個', '206個', '406個'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 14,
    pregunta: '¿Cuál es el órgano más grande del cuerpo humano?',
    preguntaJa: '人体で一番大きい器官は？',
    opciones: ['Hígado', 'Cerebro', 'Pulmones', 'Piel'],
    opcionesJa: ['肝臓', '脳', '肺', '皮膚'],
    correcta: 3,
    tiempo: 20,
  },

  // ---------- Geografía ----------
  {
    id: 15,
    pregunta: '¿Cuál es la capital de Australia?',
    preguntaJa: 'オーストラリアの首都は？',
    opciones: ['Sídney', 'Canberra', 'Melbourne', 'Perth'],
    opcionesJa: ['シドニー', 'キャンベラ', 'メルボルン', 'パース'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 16,
    pregunta: '¿Cuál es la capital de Canadá?',
    preguntaJa: 'カナダの首都は？',
    opciones: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    opcionesJa: ['オタワ', 'トロント', 'バンクーバー', 'モントリオール'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 17,
    pregunta: '¿Cuál es la capital de Brasil?',
    preguntaJa: 'ブラジルの首都は？',
    opciones: ['Río de Janeiro', 'San Pablo', 'Brasilia', 'Salvador'],
    opcionesJa: ['リオデジャネイロ', 'サンパウロ', 'ブラジリア', 'サルバドール'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 18,
    pregunta: '¿Cuál es el país más grande del mundo?',
    preguntaJa: '世界で一番面積が大きい国は？',
    opciones: ['China', 'Estados Unidos', 'Canadá', 'Rusia'],
    opcionesJa: ['中国', 'アメリカ', 'カナダ', 'ロシア'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 19,
    pregunta: '¿Cuál es el océano más grande del mundo?',
    preguntaJa: '世界で一番大きい海洋は？',
    opciones: ['Atlántico', 'Pacífico', 'Índico', 'Ártico'],
    opcionesJa: ['大西洋', '太平洋', 'インド洋', '北極海'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 20,
    pregunta: '¿Cuál es la montaña más alta del mundo?',
    preguntaJa: '世界で一番高い山は？',
    opciones: ['K2', 'Aconcagua', 'Everest', 'Kilimanjaro'],
    opcionesJa: ['K2', 'アコンカグア', 'エベレスト', 'キリマンジャロ'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 21,
    pregunta: '¿Cuál es la montaña más alta de América?',
    preguntaJa: 'アメリカ大陸で一番高い山は？',
    opciones: ['Aconcagua', 'Denali', 'Chimborazo', 'Huascarán'],
    opcionesJa: ['アコンカグア', 'デナリ', 'チンボラソ', 'ワスカラン'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 22,
    pregunta: '¿Cuál es el río más largo de América del Sur?',
    preguntaJa: '南米で一番長い川は？',
    opciones: ['Paraná', 'Orinoco', 'Río de la Plata', 'Amazonas'],
    opcionesJa: ['パラナ川', 'オリノコ川', 'ラプラタ川', 'アマゾン川'],
    correcta: 3,
    tiempo: 20,
  },
  {
    id: 23,
    pregunta: '¿Cuál es el desierto más seco del mundo (sin contar los polos)?',
    preguntaJa: '極地を除いて、世界で一番乾燥した砂漠は？',
    opciones: ['Sahara', 'Atacama', 'Gobi', 'Kalahari'],
    opcionesJa: ['サハラ砂漠', 'アタカマ砂漠', 'ゴビ砂漠', 'カラハリ砂漠'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 24,
    pregunta: '¿En qué continente está Kenia?',
    preguntaJa: 'ケニアはどの大陸にある？',
    opciones: ['Asia', 'Oceanía', 'África', 'América'],
    opcionesJa: ['アジア', 'オセアニア', 'アフリカ', 'アメリカ大陸'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 25,
    pregunta: '¿En qué país están las pirámides de Guiza?',
    preguntaJa: 'ギザのピラミッドがある国は？',
    opciones: ['Egipto', 'México', 'Perú', 'India'],
    opcionesJa: ['エジプト', 'メキシコ', 'ペルー', 'インド'],
    correcta: 0,
    tiempo: 15,
  },

  // ---------- Historia, arte y cultura ----------
  {
    id: 26,
    pregunta: '¿Quién pintó la Mona Lisa?',
    preguntaJa: '「モナ・リザ」を描いたのは誰？',
    opciones: ['Pablo Picasso', 'Miguel Ángel', 'Vincent van Gogh', 'Leonardo da Vinci'],
    opcionesJa: ['パブロ・ピカソ', 'ミケランジェロ', 'フィンセント・ファン・ゴッホ', 'レオナルド・ダ・ヴィンチ'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 27,
    pregunta: '¿Quién pintó "La noche estrellada"?',
    preguntaJa: '「星月夜」を描いたのは誰？',
    opciones: ['Claude Monet', 'Vincent van Gogh', 'Salvador Dalí', 'Pablo Picasso'],
    opcionesJa: ['クロード・モネ', 'フィンセント・ファン・ゴッホ', 'サルバドール・ダリ', 'パブロ・ピカソ'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 28,
    pregunta: '¿Quién escribió "Don Quijote de la Mancha"?',
    preguntaJa: '『ドン・キホーテ』を書いたのは誰？',
    opciones: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Miguel de Cervantes', 'Lope de Vega'],
    opcionesJa: ['ホルヘ・ルイス・ボルヘス', 'ガブリエル・ガルシア＝マルケス', 'ミゲル・デ・セルバンテス', 'ロペ・デ・ベガ'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 29,
    pregunta: '¿En qué año llegó el ser humano a la Luna por primera vez?',
    preguntaJa: '人類が初めて月に降り立ったのは何年？',
    opciones: ['1965', '1969', '1967', '1972'],
    opcionesJa: ['1965年', '1969年', '1967年', '1972年'],
    correcta: 1,
    tiempo: 20,
  },
  {
    id: 30,
    pregunta: '¿En qué año cayó el Muro de Berlín?',
    preguntaJa: 'ベルリンの壁が崩壊したのは何年？',
    opciones: ['1989', '1985', '1991', '1995'],
    opcionesJa: ['1989年', '1985年', '1991年', '1995年'],
    correcta: 0,
    tiempo: 20,
  },
  {
    id: 31,
    pregunta: '¿Qué científico propuso la teoría de la relatividad?',
    preguntaJa: '相対性理論を提唱した科学者は？',
    opciones: ['Isaac Newton', 'Galileo Galilei', 'Nikola Tesla', 'Albert Einstein'],
    opcionesJa: ['アイザック・ニュートン', 'ガリレオ・ガリレイ', 'ニコラ・テスラ', 'アルベルト・アインシュタイン'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 32,
    pregunta: '¿Qué banda grabó el disco "Abbey Road"?',
    preguntaJa: 'アルバム『アビイ・ロード』を出したバンドは？',
    opciones: ['The Rolling Stones', 'Queen', 'The Beatles', 'Pink Floyd'],
    opcionesJa: ['ローリング・ストーンズ', 'クイーン', 'ビートルズ', 'ピンク・フロイド'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 33,
    pregunta: '¿Qué idioma se habla oficialmente en Brasil?',
    preguntaJa: 'ブラジルの公用語は？',
    opciones: ['Español', 'Portugués', 'Brasileño', 'Inglés'],
    opcionesJa: ['スペイン語', 'ポルトガル語', 'ブラジル語', '英語'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 34,
    pregunta: '¿Cuál es el idioma con más hablantes nativos del mundo?',
    preguntaJa: '母語として話す人が世界で一番多い言語は？',
    opciones: ['Chino mandarín', 'Inglés', 'Español', 'Hindi'],
    opcionesJa: ['中国語（標準中国語）', '英語', 'スペイン語', 'ヒンディー語'],
    correcta: 0,
    tiempo: 20,
  },

  // ---------- Deportes y música ----------
  {
    id: 35,
    pregunta: '¿Qué selección ganó el Mundial de fútbol de 2022?',
    preguntaJa: '2022年サッカーワールドカップの優勝国は？',
    opciones: ['Francia', 'Brasil', 'Croacia', 'Argentina'],
    opcionesJa: ['フランス', 'ブラジル', 'クロアチア', 'アルゼンチン'],
    correcta: 3,
    tiempo: 15,
  },
  {
    id: 36,
    pregunta: '¿Cuántos jugadores tiene un equipo de vóley en la cancha?',
    preguntaJa: 'バレーボールでコートに入る1チームの人数は？',
    opciones: ['5', '6', '7', '9'],
    opcionesJa: ['5人', '6人', '7人', '9人'],
    correcta: 1,
    tiempo: 15,
  },
  {
    id: 37,
    pregunta: '¿Cuántas cuerdas tiene una guitarra criolla?',
    preguntaJa: 'クラシックギターの弦は何本？',
    opciones: ['4', '5', '6', '7'],
    opcionesJa: ['4本', '5本', '6本', '7本'],
    correcta: 2,
    tiempo: 15,
  },
  {
    id: 38,
    pregunta: '¿Cuántas teclas tiene un piano estándar?',
    preguntaJa: '標準的なピアノの鍵盤はいくつ？',
    opciones: ['88', '76', '96', '104'],
    opcionesJa: ['88鍵', '76鍵', '96鍵', '104鍵'],
    correcta: 0,
    tiempo: 20,
  },

  // ---------- Curiosidades ----------
  {
    id: 39,
    pregunta: '¿De qué color es la "caja negra" de los aviones?',
    preguntaJa: '飛行機の「ブラックボックス」は何色？',
    opciones: ['Negra', 'Roja', 'Naranja', 'Amarilla'],
    opcionesJa: ['黒', '赤', 'オレンジ', '黄色'],
    correcta: 2,
    tiempo: 20,
  },
  {
    id: 40,
    pregunta: '¿Qué fruta tiene las semillas por fuera?',
    preguntaJa: '種が実の外側についている果物は？',
    opciones: ['Kiwi', 'Banana', 'Uva', 'Frutilla'],
    opcionesJa: ['キウイ', 'バナナ', 'ブドウ', 'イチゴ'],
    correcta: 3,
    tiempo: 15,
  },
];
